name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout public repository
      uses: actions/checkout@v3
      
    - name: Checkout private repository
      run: |
        git clone https://:${{ secrets.PAT_TOKEN }}@github.com/aabhinavg1/newletter_modal.git include

    - name: Copy private code into public repo
      run: |
        cp -r include/* ./src/dependencies/

    - name: Set up C++ environment
      run: sudo apt-get install -y build-essential cmake

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run tests
      run: ./build/tests
