name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout public repository
      uses: actions/checkout@v3

    - name: Checkout private repository
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        echo "Cloning the private repository..."
        git clone https://${{ secrets.PAT_TOKEN }}@github.com/aabhinavg1/newletter_modal.git include

    - name: Copy private repository code into public repo
      run: |
        echo "Copying private repository code to public repository..."
        mkdir -p ./src/dependencies/
        cp -r include/* ./src/dependencies/

    - name: Set up C++ environment
      run: |
        echo "Setting up C++ environment..."
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Build project
      run: |
        echo "Building the project..."
        mkdir build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        echo "Running tests..."
        ./build/tests
