name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        submodules: false

    - name: Clone the newsletter_modal repository
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}  # Ensure the PAT_TOKEN is available here
      run: |
        echo "Cloning the newsletter_modal repository..."
        # Use the PAT for authentication directly in the URL
        git submodule add https://$PAT_TOKEN@github.com/aabhinavg1/newsletter_modal.git src/components/newsletter_modal_updated
        git submodule update --init --recursive

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build
